DesignWeb_Project/Areas/Admin/Models/DataModel/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesignWeb_Project.Areas.Admin.Models.DataModel
{
    [Table("Contact")]
    public class Contact
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ContactID { get; set; }

        [Display(Name = "Họ Và Tên")]
        [Required(ErrorMessage = "Họ Tên Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "Họ Tên Không Được Vượt Quá 250 Kí Tự")]
        public string FullName { get; set; }



        [Display(Name = "Email")]
        [Column(TypeName = "varchar")]
        [Required(ErrorMessage = "Email Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "Email Không Được Vượt Quá 250 Kí Tự")]
        public string Email { get; set; }



        [Display(Name = "Số Điện Thoại")]
        [Column(TypeName = "varchar")]
        [Required(ErrorMessage = "Số Điện Thoại Không Được Bỏ Trống")]
        [MaxLength(11, ErrorMessage = "Số Điện Thoại Vượt Quá 11 Kí Tự")]
        public string Phone { get; set; }


        [Display(Name = "Nội dung")]
        [Column(TypeName = "ntext")]
        [Required(ErrorMessage = "Mời Bạn Nhập Nội Dung")]
        public string Content { get; set; }



        public bool ViewStatus { get; set; }

        [Display(Name = "Ngày đăng")]
        public DateTime? CreatedAt { get; set; }

    }
}

DesignWeb_Project/Areas/Admin/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DesignWeb_Project.Areas.Admin.Models.BusinessModel;
using DesignWeb_Project.Areas.Admin.Models.DataModel;
using System.IO;
using PagedList;

namespace DesignWeb_Project.Areas.Admin.Controllers
{
    [AuthorizeBusiness]
    public class ContactsController : Controller
    {
        private ConnectionDBContext db = new ConnectionDBContext();

        // GET: Admin/Contacts
        public ActionResult Index(int? page,string q)
        {
            var count_contact = (from con in db.Contacts select con.ContactID).Count();

            ViewBag.count_contact = count_contact;




            var model = from p in db.Contacts orderby p.CreatedAt descending select p;
            int pagesize = 3;
            int pageNumber = (page ?? 1);


            if (!string.IsNullOrEmpty(q))
            {
                model = model.Where(x => x.FullName.Contains(q) || x.Email.Contains(q)).OrderByDescending(x => x.CreatedAt);
            }

            ViewBag.keyword_search = q;

            return View(model.ToPagedList(pageNumber, pagesize));
        }

        // GET: Admin/Contacts/Details/5
        public ActionResult Details(int? id)
        {

            Contact contact = db.Contacts.Find(id);
            contact.ViewStatus = true;
            db.Entry(contact).State = EntityState.Modified;
            db.SaveChanges();
            return View(contact);
        }






        public ActionResult Delete(int? id)
        {

            Contact contact = db.Contacts.Find(id);

            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DesignWeb_Project/Areas/Admin/Views/Contacts/Delete.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.Contact

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DesignWeb_Project/Areas/Admin/Views/Contacts/Details.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.Contact

@{
    ViewBag.Title = "Xem chi tiết thư liên hệ";
}

<div class="curd" style="margin-right:70px;width:100%;">


    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <div class="breadcrumb">
            <div class="breadcrumb-left">
                <i class="menu-icon fa fa-comments" aria-hidden="true"></i>
                <a href="~/Admin/Contacts" class="title_bread"> Thư liên hệ</a>
                <span style="color:#ccc;margin:0px 15px;font-size:20px;"> /</span>
                <span class="title_bread"> Xem chi tiết</span>
                <span style="color:#ccc;margin:0px 15px;font-size:20px;"> /</span>
                <span class="title_bread"> @Model.FullName</span>
            </div>
            <div class="breadcrumb-add">
                @Html.ActionLink("Quay Lại", "Index", "", new { @class = "btn btn-default" })
            </div>
        </div><!-- /.breadcrumb -->


    </div>


    <div class="createandedit">

        <div class="row">

            <div class="col-xs-12 col-md-12">

                <div class="editcreate">



                    <table class="table table-responsive" style="border: 1px solid #ddd;">
                        <tr>
                            <td class="title_text">Họ tên</td>
                            <td>@Model.FullName</td>
                        </tr>

                        <tr>
                            <td class="title_text">Điện Thoại</td>
                            <td>@Model.Phone</td>
                        </tr>

                        <tr>
                            <td class="title_text">Email</td>
                            <td>@Model.Email</td>
                        </tr>

                        <tr>
                            <td class="title_text">Nội Dung</td>
                            <td>@Model.Content</td>
                        </tr>


                        <tr>
                            <td class="title_text">Điện Thoại</td>
                            <td>@Model.Phone</td>
                        </tr>

                        <tr>
                            <td class="title_text">Ngày nhận</td>
                            <td>@Model.CreatedAt</td>
                        </tr>


                    </table>

                    <div class="text-center">
                        @Html.ActionLink("Xóa Thư Liên Hệ", "Delete", new { id = Model.ContactID }, htmlAttributes: new { @class = "btn_confirm btn btn-xs btn-danger text-center" })
                    </div>

</div>

                </div>
            </div>

            <div class="text-left" style="margin-top:20px;">
                <i class="fa fa-angle-double-left" aria-hidden="true" style="color:red !important;"></i>  @Html.ActionLink("Trở lại trang trước", "Index", "", new { style = "color:red;font-size:12px;" })
            </div>

        </div>


<style>
    .table tr td{
        border:1px solid #ddd;
        color:red;
    padding: 15px 10px !important;
    }
    .title_text{
        width:25%;
        text-align:center;
        color:#000 !important;
        font-weight:bold;
    }
</style>

DesignWeb_Project/Areas/Admin/Views/Contacts/Index.cshtml
@model PagedList.IPagedList<DesignWeb_Project.Areas.Admin.Models.DataModel.Contact>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Thư liên hệ";
}

<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <div class="breadcrumb">
        <div class="breadcrumb-left">
            <i class="menu-icon fa fa-comments" aria-hidden="true"></i>
            <span class="title_bread">Tất cả thư liên hệ</span>
        </div>

    </div><!-- /.breadcrumb -->


</div>


<div class="internew-content">
    <div class="title_cat">
        <h3>Liên Hệ</h3>
    </div>


    <div class="content-layout">
        <div class="pull-left">
            <p class="count">Tổng số liên hệ: <span>@ViewBag.count_contact</span> | Tổng số trang:  <span>@Model.PageCount</span></p>
        </div>
        <div class="pull-right">
            <div class="border_search">
                @using (Html.BeginForm("Index", "Contacts", FormMethod.Get))
                {
                    <span class="next-input-add-on next-input__add-on--before">
                        <svg class="svg-next-icon svg-next-icon-size-20">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-search-reverse">
                                <svg id="next-search-reverse" class="icon-symbol--loaded" width="100%" height="100%"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M8 12c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm9.707 4.293l-4.82-4.82C13.585 10.493 14 9.296 14 8c0-3.313-2.687-6-6-6S2 4.687 2 8s2.687 6 6 6c1.296 0 2.492-.415 3.473-1.113l4.82 4.82c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414z"></path></svg></svg>
                            </use>
                        </svg>
                    </span><input type="text" placeholder="Nhập từ khóa..." value="@ViewBag.keyword_search" name="q" /><input type="submit" class="hidden" />
                }
            </div>
        </div>


    </div>

    <table class="table">
        <tr>
            <th>
                Họ tên
            </th>
            <th>
                Email
            </th>
            <th>
               Phone
            </th>

            <th>
                Ngày nhận
            </th>

            <th>Tùy chỉnh</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    <a href="/Admin/Contacts/Details/@item.ContactID">@Html.DisplayFor(modelItem => item.FullName)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>

                <td>

                    @Html.ActionLink("Xem Chi Tiết", "Details", new { id = item.ContactID }, htmlAttributes: new { @class = "view_details btn btn-xs btn-warning" })
                    @Html.ActionLink("Xóa", "Delete", new { id = item.ContactID }, htmlAttributes: new { @class = "btn_confirm btn btn-xs btn-danger" })
                </td>
            </tr>
        }

    </table>
    <div class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @q = ViewBag.keyword_search }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
    </div>

</div>