DesignWeb_Project/Areas/Admin/Models/DataModel/MenuNavigation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesignWeb_Project.Areas.Admin.Models.DataModel
{
    [Table("MenuNavigation")]
    public class MenuNavigation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MenuID { get; set; }

        [Display(Name = "Thứ tự hiển thị")]
        public int? Sequence { get; set; }

        [Display(Name = "Tên Menu")]
        [Required(ErrorMessage ="Tên Menu Không Được Bỏ Trống")]
        [MaxLength(50,ErrorMessage ="Tên Menu Không Được Quá 50 Kí Tự")]
        public string MenuName { get; set; }


        [Display(Name = "Icon hình ảnh")]
        public string IconMenu { get; set; }



        [Display(Name = "Chọn Cấp Thư Mục")]
        public int MenuParents { get; set; }

        [Display(Name = "Kiểu Trang")]
        public int PageStyle { get; set; }

        [Display(Name = "Thể Loại Trang")]
        public int? FormatPage { get; set; }

        [Display(Name = "Nhóm Liên Kết")]
        public int? GroupLink { get; set; }

        [AllowHtml]
        [Column(TypeName = "ntext")]
        [Display(Name = "Trang Nội Dung")]
        public string PageContent { get; set; }

        [Display(Name = "Link Liên Kết")]
        [MaxLength(250, ErrorMessage = "Link Liên Kết Không Được Quá 250 Kí Tự")]
        public string PageLink { get; set; }


        [Display(Name = "Tiêu đề trang")]
        [MaxLength(250, ErrorMessage = "MetaTitle Không Được Quá 250 Kí Tự")]
        public string MetaTitle { get; set; }

        [Display(Name = "Từ Khóa SEO")]
        [MaxLength(250, ErrorMessage = "MetaKeyWord Không Được Quá 250 Kí Tự")]
        public string MetaKeyword { get; set; }


        [Display(Name = "Mô tả SEO")]
        public string MetaDescription { get; set; }


        [Display(Name = "Ngày Tạo")]
        public DateTime? CreatedAt { get; set; }

        [Display(Name = "Trạng Thái")]
        public bool Status { get; set; }


    }
}

DesignWeb_Project/Areas/Admin/Controllers/MenuNavigationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DesignWeb_Project.Areas.Admin.Models.BusinessModel;
using DesignWeb_Project.Areas.Admin.Models.DataModel;
using PagedList;
using System.IO;

namespace DesignWeb_Project.Areas.Admin.Controllers
{
    [AuthorizeBusiness]
    public class MenuNavigationsController : Controller
    {
        private ConnectionDBContext db = new ConnectionDBContext();

        // GET: Admin/MenuNavigations
        public ActionResult Index(int? page,string q)
        {
            var count_menu = (from menu in db.MenuNavigations select menu.MenuID).Count();

            ViewBag.count_menu = count_menu;


            var parent_menu = db.MenuNavigations.Where(x=>x.MenuParents == x.MenuID).ToList();

            ViewBag.parent_menu = parent_menu;

            var model = from p in db.MenuNavigations orderby p.Sequence descending select p;
            int pagesize = 15;
            int pageNumber = (page ?? 1);


            if (!string.IsNullOrEmpty(q))
            {
                model = model.Where(x => x.MenuName.Contains(q) || x.Sequence.ToString().Contains(q)).OrderByDescending(x => x.Sequence);
            }

            ViewBag.keyword_search = q;

            return View(model.ToPagedList(pageNumber, pagesize));
        }




        public JsonResult GetDataCategorys()
        {
            var category = db.Categorys.Select(x => new
            {
                IdCate = x.CategoryID,
                NameCate = x.CategoryName
            }).ToList();
            return Json(category, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDataBlogs()
        {
            var blog = db.Blogs.Select(x => new
            {
                IdBlog = x.BlogID,
                NameBlog = x.BlogName
            }).ToList();
            return Json(blog, JsonRequestBehavior.AllowGet);
        }

        

        public ActionResult Create()
        {
            var listParent = db.MenuNavigations.AsEnumerable();
            
            
            ViewBag.item = listParent.ToList();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( MenuNavigation menuNavigation, HttpPostedFileBase image_icon, bool status_mi)
        {
            if (ModelState.IsValid)
            {
                bool tus;
                if (status_mi == true)
                {
                    tus = true;
                }
                else
                {
                    tus = false;
                }



                if (image_icon != null)
                {
                    var filename = Path.GetFileName(image_icon.FileName);
                    var path = Path.Combine(Server.MapPath("~/Upload/Images"), filename);


                    image_icon.SaveAs(path);
                    menuNavigation.IconMenu = "/Upload/Images/" + image_icon.FileName;
                }

                menuNavigation.Status = tus;
                menuNavigation.CreatedAt = DateTime.Now;
                db.MenuNavigations.Add(menuNavigation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            var listParent = db.MenuNavigations.AsEnumerable();
            ViewBag.item = listParent.ToList();


            return View(menuNavigation);
        }

        // GET: Admin/MenuNavigations/Edit/5
        public ActionResult Edit(int? id)
        {
            var listParent = db.MenuNavigations.AsEnumerable();

            ViewBag.item = listParent.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuNavigation menuNavigation = db.MenuNavigations.Find(id);
            if (menuNavigation == null)
            {
                return HttpNotFound();
            }
            return View(menuNavigation);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MenuNavigation menuNavigation, HttpPostedFileBase image_icon)
        {
            if (ModelState.IsValid)
            {



                if (image_icon != null)
                {
                    var filename = Path.GetFileName(image_icon.FileName);
                    var path = Path.Combine(Server.MapPath("~/Upload/Images"), filename);


                    image_icon.SaveAs(path);
                    menuNavigation.IconMenu = "/Upload/Images/" + image_icon.FileName;
                }


                db.Entry(menuNavigation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menuNavigation);
        }

        // GET: Admin/MenuNavigations/Delete/5
        public ActionResult Delete(int? id)
        {
            MenuNavigation nav = db.MenuNavigations.Find(id);
            if (nav.IconMenu != "")
            {
                var filename = Path.GetFileName(nav.IconMenu);
                System.IO.File.Delete(Request.PhysicalApplicationPath + "/Upload/Images/" + filename);
            }

            db.MenuNavigations.Remove(nav);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DesignWeb_Project/Areas/Admin/Views/MenuNavigations/Create.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.MenuNavigation

@{
    ViewBag.Title = "Thêm mới Menu";
}

<div class="curd" style="margin-right:70px;width:100%;">

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <div class="breadcrumb">
                <div class="breadcrumb-left">
                    <i class="menu-icon fa fa-user" aria-hidden="true"></i>
                    <a href="~/Admin/MenuNavigations" class="title_bread"> Danh sách Menu</a>
                    <span style="color:#ccc;margin:0px 15px;font-size:20px;"> /</span>
                    <span class="title_bread"> Thêm Mới</span>
                </div>
                <div class="breadcrumb-add">
                    @Html.ActionLink("Hủy", "Index", "", new { @class = "btn btn-default" })
                    <input type="submit" value="Lưu Lại" class="btn btn-primary" />
                </div>
            </div><!-- /.breadcrumb -->


        </div>



        <div class="createandedit">

            <div class="row">
                @Html.AntiForgeryToken()


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })







                <div class="col-xs-12 col-md-8">

                    <div class="editcreate">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Sequence, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Sequence, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sequence, "", new { @class = "text-danger" })
        
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuName, htmlAttributes: new { @class = "control-label" })
                        
                                @Html.EditorFor(model => model.MenuName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                 
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.IconMenu, htmlAttributes: new { @class = "control-label" })
                            <input type="file" name="image_icon" id="uploadFile" onchange="readURL(this);" />

                            <div id="showImage">
                                <img id="image_showed" />
                            </div>

                        </div>





                        <div class="form-group page_content">
                            @Html.LabelFor(model => model.PageContent, htmlAttributes: new { @class = "control-label" })
                 
                                @Html.TextAreaFor(model => model.PageContent, new { htmlAttributes = new { @class = "form-control" }, id = "txtContent" })
                                @Html.ValidationMessageFor(model => model.PageContent, "", new { @class = "text-danger" })
                
                        </div>

                        <div class="form-group link_lienket">
                            @Html.LabelFor(model => model.PageLink, htmlAttributes: new { @class = "control-label" })
            
                                @Html.EditorFor(model => model.PageLink, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PageLink, "", new { @class = "text-danger" })

                        </div>






                        </div>

                    <div class="seo_des">
                        <div class="pen-top">
                            <div class="pull-left txt_left1">Tối ưu SEO</div>

                            <div class="pull-right txt_left2">Chỉnh sửa SEO</div>

                            <p class="text_set">Thiết lập các thẻ mô tả giúp khách hàng dễ dàng tìm thấy danh mục này trên công cụ tìm kiếm như Google.</p>



                            <div class="input_telier">
                                <div class="form-group ten-seo">
                                    @Html.LabelFor(model => model.MetaTitle, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })

                                </div>

                                <div class="form-group ten-seo">
                                    @Html.LabelFor(model => model.MetaKeyword, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.MetaKeyword, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MetaKeyword, "", new { @class = "text-danger" })

                                </div>

                                <div class="form-group ten-seo">
                                    @Html.LabelFor(model => model.MetaDescription, htmlAttributes: new { @class = "control-label" })
                                    @Html.TextAreaFor(model => model.MetaDescription, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>



                    </div>



                <div class="col-xs-12 col-md-4">
                    <div class="visible-status">
                        <p class="title_st">Hiển thị</p>
                        <div class="check-st">
                            <div class="show-st">
                                <input type="radio" name="status_mi" value="true" checked /> <span class="hideshow">Hiện</span>
                            </div>
                            <div class="show-st">
                                <input type="radio" name="status_mi" value="false" /> <span class="hideshow">Ẩn</span>
                            </div>
                        </div>

                        <div class="time-stamp">
                            <p class="title_sts"> Thời Gian:</p>
                            <input type="text" value="@DateTime.Now" disabled />
                        </div>
                    </div>

                    <div class="bot-des-more">
                        <h3 class="title_pl">Phân loại</h3>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuID, "Danh mục Cha", htmlAttributes: new { @class = "control-label" })
                            <span class="custom-dropdown custom-dropdown-white">
                                @Html.DropDownList("MenuParents", new SelectList(ViewBag.item, "MenuID", "MenuName"), new { id = "MenuParents", @class = "form-control custom-dropdown-select"})
                            </span>
                        </div>


                        <div class="form-group">
                            <label class="control-label">Chọn Kiểu Menu</label>

                            <span class="custom-dropdown custom-dropdown-white">
                                <select name="PageStyle" id="PageStyle" class="form-control custom-dropdown-select">
                                    <option value="0">===Chọn Kiểu Menu===</option>
                                    <option value="1">Nhóm Liên Kết</option>
                                    <option value="2">Trang Nội Dung</option>
                                    <option value="3">Liên Kết URL</option>
                                    <option value="4">Liên Kết Trang Liên Hệ</option>
                                </select>
                            </span>
                            @Html.ValidationMessageFor(model => model.PageStyle, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group theloai_page">

                          @Html.LabelFor(model => model.FormatPage, htmlAttributes: new { @class = "control-label" }) 
                            <span class="custom-dropdown custom-dropdown-white">
                                <select id="FormatPage" name="FormatPage" class="form-control custom-dropdown-select">
                                    <option value="0">===Chọn Thể Loại Trang===</option>
                                    <option value="1">Liên Kết Sản Phẩm</option>
                                    <option value="2">Liên Kết Bài Viết</option>

                                </select>
                            </span>
                            @Html.ValidationMessageFor(model => model.FormatPage, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group group_lienket">
                            @Html.LabelFor(model => model.GroupLink, htmlAttributes: new { @class = "control-label " })
                            <span class="custom-dropdown custom-dropdown-white">
                                <select id="GroupLink" name="GroupLink" class="form-control custom-dropdown-select">

                                </select>
                            </span>
                        </div>






                        </div>

                    </div>


                </div>
                </div>
                }

            </div>


<script type="text/javascript">
            function readURL(input) {
                if (input.files && input.files[0]) {
                    $('.noset-image').hide();
                    $('.change_image').css("display","block");
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#image_showed')
                            .attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            }
</script>


<script>

    $(document).ready(function () {
        $(".page_content").hide();
        $(".link_lienket").hide();
        $(".theloai_page").hide();
        $(".group_lienket").hide();
        $('#PageStyle').on('change', function () {
            if (this.value == '1') {

                $(".page_content textarea").val("");
                $(".link_lienket input").val("");

                $(".theloai_page").show();
                $(".link_lienket").hide();
                $(".page_content").hide();
                $(".group_lienket").hide();


                

            } else if (this.value == '2') {
                $('#FormatPage option[value=0]').attr('selected', 'selected');
                $('#GroupLink option[value=0]').attr('selected', 'selected');

                $(".link_lienket input").val("");

                $(".theloai_page").hide();
                $(".link_lienket").hide();
                $(".page_content").show();
                $(".group_lienket").hide();
            } else if (this.value == '3') {
                $('#FormatPage option[value=0]').attr('selected', 'selected');
                $('#GroupLink option[value=0]').attr('selected', 'selected');
                $(".page_content textarea").html("");



                $(".theloai_page").hide();
                $(".link_lienket").show();
                $(".page_content").hide();
                $(".group_lienket").hide();
            }
            else {
                $('#FormatPage option[value=0]').attr('selected', 'selected');
                $('#GroupLink option[value=0]').attr('selected', 'selected');
                $(".page_content textarea").val("");
                $(".link_lienket input").val("");


                $(".page_content").hide();
                $(".link_lienket").hide();
                $(".theloai_page").hide();
                $(".group_lienket").hide();
            }
        });




        $('#FormatPage').on('change', function () {
            $(".group_lienket").show();
            if (this.value == 1) {
                $('#GroupLink').html('');
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetDataCategorys")",
                    success: function (data) {

                        $.each(data, function(i, item)  
                        {  
                            $('#GroupLink').append("<option value='" + item.IdCate + "'>" + item.NameCate + "</option>");
                        });  

                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            } else if ((this.value == 2)) {
                $('#GroupLink').html('');
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetDataBlogs")",
                success: function (data) {
                    $.each(data, function(i, item)  
                    {  
                        $('#GroupLink').append("<option value='" + item.IdBlog + "'>" + item.NameBlog + "</option>");
                    });

  
                },
                error: function (responses) {
                    alert(responses.responseText);
                }
            });
            }
        });
    });



    $("#MenuParents").prepend('<option value=0 selected >Danh Mục Gốc</option>');

</script>

DesignWeb_Project/Areas/Admin/Views/MenuNavigations/Delete.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.MenuNavigation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MenuNavigation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sequence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sequence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuParents)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuParents)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FormatPage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FormatPage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PageContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PageLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKeyword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKeyword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DesignWeb_Project/Areas/Admin/Views/MenuNavigations/Index.cshtml
@model PagedList.IPagedList<DesignWeb_Project.Areas.Admin.Models.DataModel.MenuNavigation>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh sách Menu";
}

<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <div class="breadcrumb">
        <div class="breadcrumb-left">
            <i class="menu-icon fa fa-bars" aria-hidden="true"></i>
            <span class="title_bread"> Danh sách Menu </span>
        </div>
        <div class="breadcrumb-add">
            @Html.ActionLink("Thêm Mới Menu", "Create")
        </div>
    </div><!-- /.breadcrumb -->


</div>

<div class="internew-content">
    <div class="title_cat">
        <h3>Danh Sách Tất Cả Menu</h3>
    </div>




    <div class="content-layout">
        <div class="pull-left">
            <p class="count">Tổng số menu: <span>@ViewBag.count_menu</span> | Tổng số trang:  <span>@Model.PageCount</span></p>
        </div>
        <div class="pull-right">
            <div class="border_search">
                @using (Html.BeginForm("Index", "MenuNavigations", FormMethod.Get))
                {
                    <span class="next-input-add-on next-input__add-on--before">
                        <svg class="svg-next-icon svg-next-icon-size-20">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-search-reverse">
                                <svg id="next-search-reverse" class="icon-symbol--loaded" width="100%" height="100%"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M8 12c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm9.707 4.293l-4.82-4.82C13.585 10.493 14 9.296 14 8c0-3.313-2.687-6-6-6S2 4.687 2 8s2.687 6 6 6c1.296 0 2.492-.415 3.473-1.113l4.82 4.82c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414z"></path></svg></svg>
                            </use>
                        </svg>
                    </span><input type="text" placeholder="Nhập từ khóa..." value="@ViewBag.keyword_search" name="q" /><input type="submit" class="hidden" />
                }
            </div>
        </div>
    </div>

    <table class="table">
        <tr>
            <th width="110px;">
                Thứ tự sắp xếp
            </th>
            <th>
                Tên Menu
            </th>

            <th>
                Danh Mục Cha
            </th>

            <th>
                Kiểu trang
            </th>



            <th>
                Ngày tạo
            </th>
            <th>
                Trạng thái
            </th>
            <th>Tùy chỉnh</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => item.Sequence)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MenuName)
                </td>
                <td>
                    @{
                        if (item.MenuParents == 0)
                        {
                            <span>Danh Mục Gốc</span>
                        }
                        else
                        {
                            foreach (var items in ViewBag.parent_menu)
                            {
                                <span>@items.MenuName</span>
                            }

                        }
                    }
                </td>
                <td>
                   @if(item.PageStyle == 1)
                   {
                       <span>Trang Liên Kết</span>
                   }
                   else if (item.PageStyle == 2)
                   {
                    <span>Trang Nội Dung</span>
                   }
                   else if (item.PageStyle == 3)
                   {
                    <span>Liên Kết URL</span>
                   }
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @{
                        if (item.Status == true)
                        {
                            <p class="btn btn-success btn-xs text-center">Active</p>
                        }
                        else
                        {
                            <p class="btn btn-danger btn-xs text-center">Disible</p>
                        }
                    }
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.MenuID }, htmlAttributes: new { @class = "view_sua btn btn-xs btn-success" })
                    @Html.ActionLink("Xóa", "Delete", new { id = item.MenuID }, htmlAttributes: new { @class = "btn_confirm btn btn-xs btn-danger" })
                </td>
            </tr>
        }

    </table>

    <div class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @q = ViewBag.keyword_search }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
    </div>

</div>