DesignWeb_Project/Areas/Admin/Models/DataModel/Slide.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace DesignWeb_Project.Areas.Admin.Models.DataModel
{

    [Table("Slide")]
    public class Slide
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SliderID { get; set; }


        [Display(Name = "Thứ tự sắp xếp")]
        [Required(ErrorMessage ="Thứ tự sắp xếp không được bỏ trống")]
        public int SortID { get; set; }

        [Display(Name = "Tên Slide")]
        [MaxLength(250, ErrorMessage = "Tên Sản Phẩm Không Được Vượt Quá 250 Kí Tự")]
        public string SliderName { get; set; }

        [Display(Name = "Mô tả Slide")]
        public string Description { get; set; }


        [Display(Name = "Hình Ảnh Slide")]
        public string Images { get; set; }


        [Display(Name = "URL Liên Kết")]
        [MaxLength(250, ErrorMessage = "URL liên kết Không Được Vượt Quá 250 Kí Tự")]
        public string URL { get; set; }


        [Display(Name = "Trạng Thái")]
        public bool Status { get; set; }

    }
}

DesignWeb_Project/Areas/Admin/Controllers/SlidesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DesignWeb_Project.Areas.Admin.Models.BusinessModel;
using DesignWeb_Project.Areas.Admin.Models.DataModel;
using PagedList;
using System.IO;

namespace DesignWeb_Project.Areas.Admin.Controllers
{
    [AuthorizeBusiness]
    public class SlidesController : Controller
    {
        private ConnectionDBContext db = new ConnectionDBContext();

        // GET: Admin/Slides
        public ActionResult Index(int? page, string q)
        {
            var count_slide = (from slider in db.Slides select slider.SliderID).Count();

            ViewBag.count_slide = count_slide;




            var model = from p in db.Slides orderby p.SortID descending select p;
            int pagesize = 15;
            int pageNumber = (page ?? 1);


            if (!string.IsNullOrEmpty(q))
            {
                model = model.Where(x => x.SliderName.Contains(q) || x.Description.Contains(q)).OrderByDescending(x => x.SortID);
            }

            ViewBag.keyword_search = q;

            return View(model.ToPagedList(pageNumber, pagesize));
        }




        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Slide slide, HttpPostedFileBase image_avatar)
        {
            if (ModelState.IsValid)
            {


                if (image_avatar != null)
                {
                    var filename = Path.GetFileName(image_avatar.FileName);
                    var path = Path.Combine(Server.MapPath("~/Upload/Images"), filename);


                    image_avatar.SaveAs(path);
                    slide.Images = "/Upload/Images/" + image_avatar.FileName;
                }
                else
                {
                    slide.Images = "";
                }


                db.Slides.Add(slide);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(slide);
        }

        // GET: Admin/Slides/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Slide slide, HttpPostedFileBase image_avatars)
        {
            if (ModelState.IsValid)
            {

                if (image_avatars != null)
                {
                    var filename = Path.GetFileName(image_avatars.FileName);
                    var path = Path.Combine(Server.MapPath("~/Upload/Images"), filename);
                    image_avatars.SaveAs(path);
                    slide.Images = "/Upload/Images/" + image_avatars.FileName;
                }


                db.Entry(slide).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slide);
        }

        // GET: Admin/Slides/Delete/5
        public ActionResult Delete(int? id)
        {

            Slide slide = db.Slides.Find(id);

            if (slide.Images != "")
            {
                var filename = Path.GetFileName(slide.Images);
                System.IO.File.Delete(Request.PhysicalApplicationPath + "/Upload/Images/" + filename);
            }

            db.Slides.Remove(slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DesignWeb_Project/Areas/Admin/Views/Slides/Create.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.Slide

@{
    ViewBag.Title = "Thêm mới Slide";
}

<div class="curd" style="margin-right:70px;width:100%;">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <div class="breadcrumb">
                <div class="breadcrumb-left">
                    <i class="menu-icon fa fa-user" aria-hidden="true"></i>
                    <a href="~/Admin/Slides" class="title_bread"> Danh sách Slide</a>
                    <span style="color:#ccc;margin:0px 15px;font-size:20px;"> /</span>
                    <span class="title_bread"> Thêm Mới</span>
                </div>
                <div class="breadcrumb-add">
                    @Html.ActionLink("Hủy", "Index", "", new { @class = "btn btn-default" })
                    <input type="submit" value="Lưu Lại" class="btn btn-primary" />
                </div>
            </div><!-- /.breadcrumb -->


        </div>





        <div class="createandedit">

            <div class="row">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="editcreate">

                    <div class="form-group">
                        @Html.LabelFor(model => model.SortID, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.SortID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SortID, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SliderName, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.SliderName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SliderName, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })

                        @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" }, rows = "4" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">

                        <input type="file" name="image_avatar" id="uploadFile" onchange="readURL(this);" />

                        <div id="showImage">
                            <img id="image_showed" width="100%" />
                        </div>

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label",style="float:left;margin-right:35px;" })

                            <div class="checkbox">
                                @Html.CheckBoxFor(model => model.Status, htmlAttributes: new { @checked = true })
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
              
                    </div>
                    </div>


                </div>
        </div>
    }
</div>



<script type="text/javascript">
            function readURL(input) {
                if (input.files && input.files[0]) {
                    $('.noset-image').hide();
                    $('.change_image').css("display","block");
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#image_showed')
                            .attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            }
</script>

DesignWeb_Project/Areas/Admin/Views/Slides/Delete.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.Slide

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Slide</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SortID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SortID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DesignWeb_Project/Areas/Admin/Views/Slides/Details.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.Slide

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Slide</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SortID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SortID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SliderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DesignWeb_Project/Areas/Admin/Views/Slides/Edit.cshtml
@model DesignWeb_Project.Areas.Admin.Models.DataModel.Slide

@{
    ViewBag.Title = "Chỉnh sửa Slide";
}

<div class="curd" style="margin-right:70px;width:100%;">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <div class="breadcrumb">
                <div class="breadcrumb-left">
                    <i class="menu-icon fa fa-user" aria-hidden="true"></i>
                    <a href="~/Admin/Slides" class="title_bread"> Danh sách Slide</a>
                    <span style="color:#ccc;margin:0px 15px;font-size:20px;"> /</span>
                    <span class="title_bread"> Chỉnh sửa</span>
                </div>
                <div class="breadcrumb-add">
                    @Html.ActionLink("Hủy", "Index", "", new { @class = "btn btn-default" })
                    <input type="submit" value="Lưu Lại" class="btn btn-primary" />
                </div>
            </div><!-- /.breadcrumb -->


        </div>





        <div class="createandedit">

            <div class="row">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.SliderID)
                @Html.HiddenFor(model => model.Images)
                <div class="editcreate">

                    <div class="form-group">
                        @Html.LabelFor(model => model.SortID, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.SortID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SortID, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SliderName, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.SliderName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SliderName, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })

                        @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" }, rows = "4" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">

                        <input type="file" name="image_avatars" id="uploadFile" onchange="readURL(this);" />

                        <div id="showImage">
                            <img id="image_showed" src="@Model.Images" width="100%" />
                        </div>

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label", style = "float:left;margin-right:35px;" })

                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.Status)
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>

                    </div>
                </div>


            </div>
        </div>
    }
</div>



<script type="text/javascript">
            function readURL(input) {
                if (input.files && input.files[0]) {
                    $('.noset-image').hide();
                    $('.change_image').css("display","block");
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#image_showed')
                            .attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            }
</script>

DesignWeb_Project/Areas/Admin/Views/Slides/Index.cshtml
@model PagedList.IPagedList<DesignWeb_Project.Areas.Admin.Models.DataModel.Slide>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh sách Slide";
}

<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <div class="breadcrumb">
        <div class="breadcrumb-left">
            <i class="menu-icon fa fa-tags" aria-hidden="true"></i>
            <span class="title_bread">Quản lí Slide</span>
        </div>
        <div class="breadcrumb-add">
            @Html.ActionLink("Thêm Mới", "Create")
        </div>
    </div><!-- /.breadcrumb -->


</div>


<div class="internew-content">
    <div class="title_cat">
        <h3>Danh Sách Slider</h3>
    </div>


    <div class="content-layout">
        <div class="pull-left">
            <p class="count">Tổng số slider: <span>@ViewBag.count_slide</span> | Tổng số trang:  <span>@Model.PageCount</span></p>
        </div>
        <div class="pull-right">
            <div class="border_search">
                @using (Html.BeginForm("Index", "Slides", FormMethod.Get))
                {
                    <span class="next-input-add-on next-input__add-on--before">
                        <svg class="svg-next-icon svg-next-icon-size-20">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-search-reverse">
                                <svg id="next-search-reverse" class="icon-symbol--loaded" width="100%" height="100%"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M8 12c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm9.707 4.293l-4.82-4.82C13.585 10.493 14 9.296 14 8c0-3.313-2.687-6-6-6S2 4.687 2 8s2.687 6 6 6c1.296 0 2.492-.415 3.473-1.113l4.82 4.82c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414z"></path></svg></svg>
                            </use>
                        </svg>
                    </span><input type="text" placeholder="Nhập từ khóa..." value="@ViewBag.keyword_search" name="q" /><input type="submit" class="hidden" />
                }
            </div>
        </div>
    </div>


    <table class="table">
        <tr>
            <th width="100px">
                Thứ tự sắp xếp
            </th>
            <th width="170px">
                Tên Slider
            </th>
            <th width="150px">
                Hình ảnh
            </th>

            <th width="130px;">
                Đường dẫn URL
            </th>
            <th>
                Trạng thái
            </th>
            <th>Tùy chỉnh </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => item.SortID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SliderName)
                </td>

                <td>
                    <img src="@item.Images" style="height:60px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.URL)
                </td>
                <td>
                    @{
                        if (item.Status == true)
                        {
                            <p class="btn btn-success btn-xs text-center">Active</p>
                        }
                        else
                        {
                            <p class="btn btn-danger btn-xs text-center">Disible</p>
                        }
                    }
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.SliderID }, htmlAttributes: new { @class = "view_sua btn btn-xs btn-success" })
                    @Html.ActionLink("Xóa", "Delete", new { id = item.SliderID }, htmlAttributes: new { @class = "btn_confirm btn btn-xs btn-danger" })
                </td>
            </tr>
                        }

    </table>

    <div class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @q = ViewBag.keyword_search }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
    </div>
</div>